server:
  port: 8080
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/produtos_gxoe
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    driverClassName: org.postgresql.Driver
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: samuelduartedecordova@gmail.com
    password: "kvis iizy jwpl stit"
    port: '587'
